### ISSUE TITLE
Menu Coloration

### ISSUE THREAD

**Issue by miketruax** [mikejunt/week-1-project#1]
I would suggest having a background color for the menu. It helps to make the menu stand apart from the rest of the page.

**Comment by mikejunt** [comment]
I liked this and turned it into adjusting the color scheme so the menu pills have a set color separate from the background, and changed the hover color to be of greater contrast to the; the previous dark blue hover is now the active pill, the two inactive pills are the same color at 0.8 density ,and the brighter blue that was the active pill is now the hover color.
