### ISSUE TITLE
Side menu for items on smaller resolutions

### ISSUE THREAD

**Issue by miketruax** [mikejunt/week-1-project#2]
You should look at what kind of style you want for the side menu on the "for sale" section at smaller resolutions. What you have now does work, but it is less than ideal given the fact that it takes up a ton of the page. I would suggest that you either move it to the top or now that you have access to JS, have it disappear and be accessible by a button or something to allow for the content to take up more of the page.

**Comment by mikejunt** [comment]
Good idea.   Menu now disappears below 576px and reappears above that.
